// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: relay_server.proto
// Original file comments:
// Copyright 2015, Google Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of Google Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
#ifndef GRPC_relay_5fserver_2eproto__INCLUDED
#define GRPC_relay_5fserver_2eproto__INCLUDED

#include "relay_server.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace py_server {

// The greeting service definition.
class RelayServer final {
 public:
  static constexpr char const* service_full_name() {
    return "py_server.RelayServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // gets state of appliance
    virtual ::grpc::Status get_state(::grpc::ClientContext* context, const ::py_server::Details& request, ::py_server::State* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::py_server::State>> Asyncget_state(::grpc::ClientContext* context, const ::py_server::Details& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::py_server::State>>(Asyncget_stateRaw(context, request, cq));
    }
    // sets state of appliance
    virtual ::grpc::Status set_state(::grpc::ClientContext* context, const ::py_server::Details& request, ::py_server::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::py_server::Response>> Asyncset_state(::grpc::ClientContext* context, const ::py_server::Details& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::py_server::Response>>(Asyncset_stateRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::py_server::State>* Asyncget_stateRaw(::grpc::ClientContext* context, const ::py_server::Details& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::py_server::Response>* Asyncset_stateRaw(::grpc::ClientContext* context, const ::py_server::Details& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status get_state(::grpc::ClientContext* context, const ::py_server::Details& request, ::py_server::State* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::py_server::State>> Asyncget_state(::grpc::ClientContext* context, const ::py_server::Details& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::py_server::State>>(Asyncget_stateRaw(context, request, cq));
    }
    ::grpc::Status set_state(::grpc::ClientContext* context, const ::py_server::Details& request, ::py_server::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::py_server::Response>> Asyncset_state(::grpc::ClientContext* context, const ::py_server::Details& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::py_server::Response>>(Asyncset_stateRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::py_server::State>* Asyncget_stateRaw(::grpc::ClientContext* context, const ::py_server::Details& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::py_server::Response>* Asyncset_stateRaw(::grpc::ClientContext* context, const ::py_server::Details& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_get_state_;
    const ::grpc::RpcMethod rpcmethod_set_state_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // gets state of appliance
    virtual ::grpc::Status get_state(::grpc::ServerContext* context, const ::py_server::Details* request, ::py_server::State* response);
    // sets state of appliance
    virtual ::grpc::Status set_state(::grpc::ServerContext* context, const ::py_server::Details* request, ::py_server::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_get_state : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_get_state() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_get_state() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_state(::grpc::ServerContext* context, const ::py_server::Details* request, ::py_server::State* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_state(::grpc::ServerContext* context, ::py_server::Details* request, ::grpc::ServerAsyncResponseWriter< ::py_server::State>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_set_state : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_set_state() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_set_state() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status set_state(::grpc::ServerContext* context, const ::py_server::Details* request, ::py_server::Response* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestset_state(::grpc::ServerContext* context, ::py_server::Details* request, ::grpc::ServerAsyncResponseWriter< ::py_server::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_get_state<WithAsyncMethod_set_state<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_get_state : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_get_state() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_get_state() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_state(::grpc::ServerContext* context, const ::py_server::Details* request, ::py_server::State* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_set_state : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_set_state() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_set_state() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status set_state(::grpc::ServerContext* context, const ::py_server::Details* request, ::py_server::Response* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_get_state : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_get_state() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::py_server::Details, ::py_server::State>(std::bind(&WithStreamedUnaryMethod_get_state<BaseClass>::Streamedget_state, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_get_state() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status get_state(::grpc::ServerContext* context, const ::py_server::Details* request, ::py_server::State* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedget_state(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::py_server::Details,::py_server::State>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_set_state : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_set_state() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::StreamedUnaryHandler< ::py_server::Details, ::py_server::Response>(std::bind(&WithStreamedUnaryMethod_set_state<BaseClass>::Streamedset_state, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_set_state() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status set_state(::grpc::ServerContext* context, const ::py_server::Details* request, ::py_server::Response* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedset_state(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::py_server::Details,::py_server::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_get_state<WithStreamedUnaryMethod_set_state<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_get_state<WithStreamedUnaryMethod_set_state<Service > > StreamedService;
};

}  // namespace py_server


#endif  // GRPC_relay_5fserver_2eproto__INCLUDED
