# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relay_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='relay_server.proto',
  package='py_server',
  syntax='proto3',
  serialized_pb=_b('\n\x12relay_server.proto\x12\tpy_server\"X\n\x04\x44\x61ta\x12\x11\n\troom_name\x18\x01 \x01(\t\x12\x16\n\x0e\x61ppliance_type\x18\x02 \x01(\t\x12\x16\n\x0e\x61ppliance_name\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\x05\"\x16\n\x05State\x12\r\n\x05value\x18\x01 \x01(\x05\"\x19\n\x08Response\x12\r\n\x05value\x18\x01 \x01(\x05\x32t\n\x0bRelayServer\x12\x30\n\tget_state\x12\x0f.py_server.Data\x1a\x10.py_server.State\"\x00\x12\x33\n\tset_state\x12\x0f.py_server.Data\x1a\x13.py_server.Response\"\x00\x62\x06proto3')
)




_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='py_server.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='room_name', full_name='py_server.Data.room_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appliance_type', full_name='py_server.Data.appliance_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appliance_name', full_name='py_server.Data.appliance_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='py_server.Data.state', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=121,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='py_server.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='py_server.State.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=145,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='py_server.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='py_server.Response.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=172,
)

DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'relay_server_pb2'
  # @@protoc_insertion_point(class_scope:py_server.Data)
  ))
_sym_db.RegisterMessage(Data)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), dict(
  DESCRIPTOR = _STATE,
  __module__ = 'relay_server_pb2'
  # @@protoc_insertion_point(class_scope:py_server.State)
  ))
_sym_db.RegisterMessage(State)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'relay_server_pb2'
  # @@protoc_insertion_point(class_scope:py_server.Response)
  ))
_sym_db.RegisterMessage(Response)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class RelayServerStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.get_state = channel.unary_unary(
          '/py_server.RelayServer/get_state',
          request_serializer=Data.SerializeToString,
          response_deserializer=State.FromString,
          )
      self.set_state = channel.unary_unary(
          '/py_server.RelayServer/set_state',
          request_serializer=Data.SerializeToString,
          response_deserializer=Response.FromString,
          )


  class RelayServerServicer(object):
    """The greeting service definition.
    """

    def get_state(self, request, context):
      """gets state of appliance
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def set_state(self, request, context):
      """sets state of appliance
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_RelayServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'get_state': grpc.unary_unary_rpc_method_handler(
            servicer.get_state,
            request_deserializer=Data.FromString,
            response_serializer=State.SerializeToString,
        ),
        'set_state': grpc.unary_unary_rpc_method_handler(
            servicer.set_state,
            request_deserializer=Data.FromString,
            response_serializer=Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'py_server.RelayServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaRelayServerServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The greeting service definition.
    """
    def get_state(self, request, context):
      """gets state of appliance
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def set_state(self, request, context):
      """sets state of appliance
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaRelayServerStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The greeting service definition.
    """
    def get_state(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """gets state of appliance
      """
      raise NotImplementedError()
    get_state.future = None
    def set_state(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """sets state of appliance
      """
      raise NotImplementedError()
    set_state.future = None


  def beta_create_RelayServer_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('py_server.RelayServer', 'get_state'): Data.FromString,
      ('py_server.RelayServer', 'set_state'): Data.FromString,
    }
    response_serializers = {
      ('py_server.RelayServer', 'get_state'): State.SerializeToString,
      ('py_server.RelayServer', 'set_state'): Response.SerializeToString,
    }
    method_implementations = {
      ('py_server.RelayServer', 'get_state'): face_utilities.unary_unary_inline(servicer.get_state),
      ('py_server.RelayServer', 'set_state'): face_utilities.unary_unary_inline(servicer.set_state),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_RelayServer_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('py_server.RelayServer', 'get_state'): Data.SerializeToString,
      ('py_server.RelayServer', 'set_state'): Data.SerializeToString,
    }
    response_deserializers = {
      ('py_server.RelayServer', 'get_state'): State.FromString,
      ('py_server.RelayServer', 'set_state'): Response.FromString,
    }
    cardinalities = {
      'get_state': cardinality.Cardinality.UNARY_UNARY,
      'set_state': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'py_server.RelayServer', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
